const stations=[
  {name:'Guadalajara Hbf',code:'GDL',lines:'ICE · IC · RE · S-Bahn'},
  {name:'Löwenstadt Hbf',code:'LOE',lines:'ICE · IC · RE'},
  {name:'Karlsburg Hbf',code:'KAR',lines:'ICE · IC · RE'},
  {name:'Golfhafen Hbf',code:'GOH',lines:'ICE · IC · RE'},
  {name:'Pazifikhafen Hbf',code:'PAZ',lines:'ICE · IC · RE'},
  {name:'Silberstadt Hbf',code:'SIL',lines:'ICE · IC · RE'},
  {name:'Badenquellen Hbf',code:'BAD',lines:'ICE · IC · RE'},
  {name:'Seeburg Hbf',code:'SEE',lines:'ICE · IC · RE'},
  {name:'Vulkanstadt Hbf',code:'VUL',lines:'IC · RE'},
  {name:'Sankt Ludwig Hbf',code:'SLU',lines:'ICE · IC · RE'},
  {name:'Chapala Flughafen',code:'CHA',lines:'Airport Express · ICE'},
  {name:'Tequila Mitte',code:'TEQ',lines:'RE · S-Bahn'},
  {name:'Kaiserstadt Hbf',code:'KAI',lines:'ICE · IC · RE'},
  {name:'Manzanillo Hafen',code:'MAN',lines:'IC · RE · Cargo'},
  {name:'Tepitz Hbf',code:'TEP',lines:'IC · RE'}
];
const copy={
  de:{home:'Start',search:'Suchen',tickets:'Tickets',profile:'Profil',greeting:'Guten Morgen',hero:'Die ganze Republik. Eine Verbindung.',up:'DEINE REISE',next:'Als Nächstes',all:'Alle',noTrip:'Noch keine Reise gebucht',noTripSub:'Finde deine nächste Verbindung.',planner:'REISEPLANER',searchTitle:'Verbindung suchen',connections:'Verbindungen',best:'Beste Verbindung',onTime:'Pünktlich',choose:'Auswählen',direct:'Direkt',ticketsTitle:'Meine Tickets',noTickets:'Keine Tickets',noTicketsSub:'Gebuchte Reisen erscheinen hier.',journeys:'Reisen',language:'Sprache',appearance:'Darstellung',favorites:'Favoriten',from:'Von',to:'Nach',date:'Datum',time:'Uhrzeit',passengers:'Reisende',class:'Klasse',searchButton:'Verbindung suchen'},
  es:{home:'Inicio',search:'Buscar',tickets:'Billetes',profile:'Perfil',greeting:'Buenos días',hero:'Toda la república. Una conexión.',up:'TU VIAJE',next:'Próximo viaje',all:'Todos',noTrip:'Aún no tienes viaje',noTripSub:'Busca tu próxima conexión.',planner:'PLANIFICADOR',searchTitle:'Buscar conexión',connections:'conexiones',best:'Mejor opción',onTime:'Puntual',choose:'Elegir',direct:'Directo',ticketsTitle:'Mis billetes',noTickets:'Sin billetes',noTicketsSub:'Tus viajes reservados aparecerán aquí.',journeys:'Viajes',language:'Idioma',appearance:'Apariencia',favorites:'Favoritos',from:'Desde',to:'Hacia',date:'Fecha',time:'Hora',passengers:'Pasajeros',class:'Clase',searchButton:'Buscar conexión'},
  en:{home:'Home',search:'Search',tickets:'Tickets',profile:'Profile',greeting:'Good morning',hero:'The whole republic. One connection.',up:'YOUR JOURNEY',next:'Up next',all:'All',noTrip:'No journey booked yet',noTripSub:'Find your next connection.',planner:'JOURNEY PLANNER',searchTitle:'Search connections',connections:'connections',best:'Best option',onTime:'On time',choose:'Select',direct:'Direct',ticketsTitle:'My tickets',noTickets:'No tickets',noTicketsSub:'Booked journeys appear here.',journeys:'Journeys',language:'Language',appearance:'Appearance',favorites:'Favorites',from:'From',to:'To',date:'Date',time:'Time',passengers:'Passengers',class:'Class',searchButton:'Search connections'}
};
const state={
  tab:'home',
  language:localStorage.getItem('gb-language')||'de',
  theme:localStorage.getItem('gb-theme')||'system',
  query:JSON.parse(localStorage.getItem('gb-query')||'null')||{from:'Guadalajara Hbf',to:'Löwenstadt Hbf',date:new Date().toISOString().slice(0,10),time:'09:15',passengers:1,travelClass:'2'},
  trips:[], tickets:JSON.parse(localStorage.getItem('gb-tickets')||'[]')
};
const app=document.getElementById('app');
function t(k){return copy[state.language][k]||k}
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function persist(){localStorage.setItem('gb-language',state.language);localStorage.setItem('gb-theme',state.theme);localStorage.setItem('gb-query',JSON.stringify(state.query));localStorage.setItem('gb-tickets',JSON.stringify(state.tickets))}
function addMinutes(time,min){let [h,m]=time.split(':').map(Number),total=h*60+m+min;return `${String(Math.floor(total%1440/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function buildTrips(){const q=state.query,start=q.time||'09:15',seed=Math.max(1,Math.abs(q.from.length-q.to.length)+2),a=82+seed*7,b=a+26,c=a+58;return[
{id:'s'+Date.now(),train:'ICE Sprinter 201',cat:'ice',from:q.from,to:q.to,dep:start,arr:addMinutes(start,a),dur:`${Math.floor(a/60)}h ${a%60}m`,platform:'4',changes:0,occupancy:'mittel',status:'on',price:q.travelClass==='1'?129:79,speed:350},
{id:'i'+Date.now(),train:'ICE 417',cat:'ice',from:q.from,to:q.to,dep:addMinutes(start,21),arr:addMinutes(start,21+b),dur:`${Math.floor(b/60)}h ${b%60}m`,platform:'8',changes:0,occupancy:'niedrig',status:'delay',delay:6,price:q.travelClass==='1'?109:64,speed:320},
{id:'c'+Date.now(),train:'IC 82',cat:'ic',from:q.from,to:q.to,dep:addMinutes(start,44),arr:addMinutes(start,44+c),dur:`${Math.floor(c/60)}h ${c%60}m`,platform:'11',changes:1,occupancy:'hoch',status:'on',price:q.travelClass==='1'?82:45,speed:230}
]}
function searchPanel(full=false){return `<section class="search-panel glass">${full?`<div class="section-heading"><div><small>${t('planner')}</small><h2>${t('searchTitle')}</h2></div><span class="live-dot">Netz online</span></div>`:''}<div class="route-inputs">
<div class="field"><label>${t('from')}</label><input id="from" autocomplete="off" value="${escapeHtml(state.query.from)}"><div id="from-suggestions"></div></div>
<button class="swap-button" id="swap" aria-label="swap">⇅</button>
<div class="field"><label>${t('to')}</label><input id="to" autocomplete="off" value="${escapeHtml(state.query.to)}"><div id="to-suggestions"></div></div></div>
<div class="search-options"><label>${t('date')}<input id="date" type="date" value="${state.query.date}"></label><label>${t('time')}<input id="time" type="time" value="${state.query.time}"></label>${full?`<label>${t('passengers')}<select id="passengers"><option ${state.query.passengers==1?'selected':''}>1</option><option ${state.query.passengers==2?'selected':''}>2</option><option ${state.query.passengers==3?'selected':''}>3</option></select></label><label>${t('class')}<select id="class"><option value="2" ${state.query.travelClass==='2'?'selected':''}>2. Klasse</option><option value="1" ${state.query.travelClass==='1'?'selected':''}>1. Klasse</option></select></label>`:''}</div>
<button class="primary-button" id="search-btn">⌕ ${t('searchButton')}</button></section>`}
function home(){const ticket=state.tickets[0];return `<div class="page"><header class="topbar"><div class="brand"><div class="brand-mark"><span>G</span><span>B</span></div><div><strong>Galicisches Bahn</strong><small>Bundesrepublik Galizien</small></div></div><button class="avatar">DM</button></header>
<section class="hero-card"><div><small>${t('greeting')}</small><h1>David</h1><p>${t('hero')}</p></div><div class="hero-orbit"><span></span><b>GB</b></div></section>${searchPanel(false)}
<div class="section-heading"><div><small>${t('up')}</small><h2>${t('next')}</h2></div><button class="text-button">${t('all')}</button></div>
<section class="next-trip glass">${ticket?`<div class="next-train"><span class="train-badge ice">${ticket.train}</span><span class="status ok">${t('onTime')}</span></div><div class="next-route"><strong>${ticket.dep}</strong><div><b>${ticket.from}</b><span>${t('direct')} · Gleis ${ticket.platform}</span><b>${ticket.to}</b></div><strong>${ticket.arr}</strong></div>`:`<div class="empty-icon">▤</div><div><strong>${t('noTrip')}</strong><p>${t('noTripSub')}</p></div>`}</section>
<div class="quick-grid"><button class="quick-card"><span class="glyph">⌁</span><span><b>Live Train</b><small>ICE 201 verfolgen</small></span></button><button class="quick-card"><span class="glyph">◉</span><span><b>Netzstatus</b><small>99,7 % pünktlich</small></span></button></div></div>`}
function tripCard(x){return `<article class="trip-card glass"><div class="trip-top"><div><span class="train-badge ${x.cat}">${x.train}</span><small>${x.speed} km/h</small></div><span class="status ${x.status==='on'?'ok':'warn'}">${x.status==='on'?t('onTime'):`+${x.delay} min`}</span></div><div class="timeline"><div><strong>${x.dep}</strong><span>${x.from}</span></div><div class="rail-line"><i></i><small>${x.dur}</small><i></i></div><div><strong>${x.arr}</strong><span>${x.to}</span></div></div><div class="trip-meta"><span>🚆 Gleis ${x.platform}</span><span>◷ ${x.changes===0?t('direct'):x.changes+'×'}</span><span>◉ ${x.occupancy}</span></div><div class="trip-footer"><div><small>Flexpreis</small><strong>${x.price} GM</strong></div><button class="secondary-button book" data-id="${x.id}">${t('choose')} ›</button></div></article>`}
function searchPage(){return `<div class="page"><div class="page-title"><small>${t('planner')}</small><h1>${t('searchTitle')}</h1></div>${searchPanel(true)}${state.trips.length?`<div class="results-heading"><div><strong>${state.trips.length} ${t('connections')}</strong><small>${escapeHtml(state.query.from)} → ${escapeHtml(state.query.to)}</small></div><button class="filter-pill">${t('best')}</button></div><div class="trip-list">${state.trips.map(tripCard).join('')}</div>`:''}</div>`}
function hash(s){let v=2166136261;for(let i=0;i<s.length;i++)v=Math.imul(v^s.charCodeAt(i),16777619);return v>>>0}
function qr(value){let seed=hash(value),cells='';for(let n=0;n<441;n++){seed=(seed*1664525+1013904223+n)>>>0;let x=n%21,y=Math.floor(n/21),finder=(x<7&&y<7)||(x>=14&&y<7)||(x<7&&y>=14),on;if(finder){let lx=x>=14?x-14:x,ly=y>=14?y-14:y;on=lx===0||lx===6||ly===0||ly===6||(lx>=2&&lx<=4&&ly>=2&&ly<=4)}else on=(seed&1)===1;cells+=`<i class="${on?'on':''}"></i>`}return `<div class="qr">${cells}</div>`}
function ticketCard(x){return `<article class="ticket-pass"><div class="ticket-header"><div><small>GALICISCHES BAHN</small><strong>${x.train}</strong></div><span>${x.travelClass}. KLASSE</span></div><div class="ticket-route"><div><strong>${x.dep}</strong><span>${x.from}</span></div><b>→</b><div><strong>${x.arr}</strong><span>${x.to}</span></div></div><div class="ticket-details"><span><small>Wagen</small><b>${x.coach}</b></span><span><small>Platz</small><b>${x.seat}</b></span><span><small>Gleis</small><b>${x.platform}</b></span></div><div class="ticket-code">${qr(x.ticketId)}<div><small>Fahrgast</small><strong>David Martínez</strong><small>${x.ticketId}</small></div></div><div class="ticket-shimmer"></div></article>`}
function ticketsPage(){return `<div class="page"><div class="page-title"><small>GB WALLET</small><h1>${t('ticketsTitle')}</h1></div>${state.tickets.length?`<div class="ticket-stack">${state.tickets.map(ticketCard).join('')}</div>`:`<section class="empty-state glass"><div>🎫</div><h2>${t('noTickets')}</h2><p>${t('noTicketsSub')}</p></section>`}</div>`}
function profilePage(){return `<div class="page"><div class="profile-header"><div class="profile-avatar">DM</div><div><small>GB CARD GOLD</small><h1>David Martínez</h1><p>Mitglied seit 2081</p></div></div><section class="gb-card"><span>GALICISCHES BAHN</span><strong>GB CARD</strong><div><b>GOLD</b><small>1088 4180 2091</small></div></section><div class="stats-grid"><div class="stat glass"><strong>124</strong><span>${t('journeys')}</span></div><div class="stat glass"><strong>36.842</strong><span>km</span></div><div class="stat glass"><strong>9.420</strong><span>GB Punkte</span></div></div><section class="settings-list glass"><div class="settings-row"><span><b>⚙ ${t('language')}</b></span><select id="language"><option value="de" ${state.language==='de'?'selected':''}>Deutsch</option><option value="es" ${state.language==='es'?'selected':''}>Español</option><option value="en" ${state.language==='en'?'selected':''}>English</option></select></div><div class="settings-row"><span><b>◐ ${t('appearance')}</b></span><select id="theme"><option value="system" ${state.theme==='system'?'selected':''}>System</option><option value="light" ${state.theme==='light'?'selected':''}>Light</option><option value="dark" ${state.theme==='dark'?'selected':''}>Dark</option></select></div><div class="settings-row"><span><b>☆ ${t('favorites')}</b></span><em>3</em></div></section></div>`}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));app.innerHTML=state.tab==='home'?home():state.tab==='search'?searchPage():state.tab==='tickets'?ticketsPage():profilePage();bind()}
function bind(){document.getElementById('swap')?.addEventListener('click',()=>{[state.query.from,state.query.to]=[state.query.to,state.query.from];persist();render()});['from','to'].forEach(id=>{const input=document.getElementById(id);if(!input)return;input.addEventListener('input',()=>{state.query[id]=input.value;showSuggestions(id,input.value)});input.addEventListener('focus',()=>showSuggestions(id,input.value));input.addEventListener('blur',()=>setTimeout(()=>{const el=document.getElementById(id+'-suggestions');if(el)el.innerHTML=''},160))});document.getElementById('date')?.addEventListener('change',e=>state.query.date=e.target.value);document.getElementById('time')?.addEventListener('change',e=>state.query.time=e.target.value);document.getElementById('passengers')?.addEventListener('change',e=>state.query.passengers=Number(e.target.value));document.getElementById('class')?.addEventListener('change',e=>state.query.travelClass=e.target.value);document.getElementById('search-btn')?.addEventListener('click',()=>{persist();state.trips=buildTrips();state.tab='search';render()});document.querySelectorAll('.book').forEach(b=>b.addEventListener('click',()=>{const x=state.trips.find(t=>t.id===b.dataset.id);if(!x)return;state.tickets.unshift({...x,ticketId:'GB-'+Date.now().toString(36).toUpperCase(),coach:'5',seat:state.query.travelClass==='1'?'18A':'42F',travelClass:state.query.travelClass});persist();toast('Ticket gespeichert');state.tab='tickets';setTimeout(render,260)}));document.getElementById('language')?.addEventListener('change',e=>{state.language=e.target.value;persist();render()});document.getElementById('theme')?.addEventListener('change',e=>{state.theme=e.target.value;persist();applyTheme();render()})}
function showSuggestions(id,value){const box=document.getElementById(id+'-suggestions'),matches=stations.filter(s=>(s.name+' '+s.code).toLowerCase().includes(value.toLowerCase())).slice(0,6);box.innerHTML=`<div class="suggestions">${matches.map(s=>`<button data-name="${s.name}"><span><strong>${s.name}</strong><small>${s.lines}</small></span><b>${s.code}</b></button>`).join('')}</div>`;box.querySelectorAll('button').forEach(b=>b.addEventListener('mousedown',()=>{state.query[id]=b.dataset.name;persist();render()}))}
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),1700)}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;render()}));applyTheme();render();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
