import {STATIONS,RAIL_EDGES,getStation,SERVICE_ALERTS} from './data.js';
const adjacency=new Map();
for(const [a,b,minutes,modes] of RAIL_EDGES){if(!adjacency.has(a))adjacency.set(a,[]);if(!adjacency.has(b))adjacency.set(b,[]);adjacency.get(a).push({to:b,minutes,modes});adjacency.get(b).push({to:a,minutes,modes});}
function shortestPath(from,to,allowed=null){const dist=new Map([[from,0]]),prev=new Map(),queue=new Set(STATIONS.map(s=>s.id));while(queue.size){let u=null,best=Infinity;for(const id of queue){const d=dist.get(id)??Infinity;if(d<best){best=d;u=id}}if(u===null||u===to)break;queue.delete(u);for(const e of adjacency.get(u)||[]){if(allowed&&!e.modes.some(m=>allowed.includes(m)))continue;const alt=best+e.minutes;if(alt<(dist.get(e.to)??Infinity)){dist.set(e.to,alt);prev.set(e.to,{id:u,edge:e})}}}if(!dist.has(to))return null;const ids=[];let cursor=to;while(cursor){ids.unshift(cursor);if(cursor===from)break;cursor=prev.get(cursor)?.id}const edges=[];for(let i=0;i<ids.length-1;i++){edges.push((adjacency.get(ids[i])||[]).find(e=>e.to===ids[i+1]))}return{ids,edges,minutes:dist.get(to)};}
const addTime=(time,mins)=>{const [h,m]=time.split(':').map(Number);const n=(h*60+m+mins+1440)%1440;return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
const typeSpecs={ICE:{speed:.78,price:.34},IC:{speed:.9,price:.26},EC:{speed:.92,price:.31},RE:{speed:1.15,price:.16},IR:{speed:1.02,price:.20},NJ:{speed:1.26,price:.39}};
export function createJourneys(search){const intl=getStation(search.toId)?.country==='MX'||getStation(search.fromId)?.country==='MX';const hour=Number(search.time.slice(0,2));const candidateTypes=intl?['EC','ICE','IC',...(hour>=19||hour<6?['NJ']:[])]:['ICE','IC','RE',...(hour>=20||hour<5?['NJ']:[])];const results=[];candidateTypes.forEach((type,index)=>{let path=shortestPath(search.fromId,search.toId,type==='NJ'?['NJ','EC','IC','ICE']:type==='EC'?['EC','ICE','IC']:type==='ICE'?['ICE','IC','EC']:type==='IC'?['IC','ICE','RE','IR']:['RE','IR','S']);if(!path)path=shortestPath(search.fromId,search.toId);if(!path)return;const spec=typeSpecs[type];const base=Math.round(path.minutes*spec.speed);const border=intl?45:0;const alert=SERVICE_ALERTS.find(a=>a.modes.includes(type));const delay=(alert?alert.delay:((index*3)%7))+(index===2?14:0);const departure=addTime(search.time,index*27);const duration=base+border+delay;const classFactor=String(search.travelClass)==='1'?1.42:1;const passenger=Math.max(1,Number(search.passengers)||1);const price=Math.max(22,Math.round(path.minutes*spec.price*classFactor*passenger));const changes=Math.max(0,Math.min(2,path.ids.length>5?1:0)+(type==='RE'&&path.ids.length>4?1:0));let connection='safe';if(changes&&delay>=10)connection='risk';if(changes&&delay>=18)connection='missed';results.push({id:`${type}-${search.fromId}-${search.toId}-${departure}`,type,train:`${type} ${type==='ICE'?100+index*6:type==='IC'?600+index*7:type==='EC'?18+index*2:type==='NJ'?490+index:7400+index*13}`,fromId:search.fromId,toId:search.toId,from:getStation(search.fromId).name,to:getStation(search.toId).name,date:search.date,departure,arrival:addTime(departure,duration),duration,baseMinutes:path.minutes,path:path.ids,price,delay,changes,platform:String(2+(index*3)%12),travelClass:String(search.travelClass),passengers:passenger,international:intl,borderMinutes:border,connection,night:type==='NJ'});});return results.sort((a,b)=>a.departure.localeCompare(b.departure));}
export function planUrban(network,from,to){if(from===to)return null;const lines=network.lines;const queue=[{stop:from,steps:[],used:[]}],seen=new Set([from]);while(queue.length){const cur=queue.shift();for(const line of lines.filter(l=>l.stops.includes(cur.stop))){const start=line.stops.indexOf(cur.stop);for(const dir of [-1,1]){for(let i=start+dir;i>=0&&i<line.stops.length;i+=dir){const stop=line.stops[i];const segment={lineId:line.id,color:line.color,mode:line.mode,from:cur.stop,to:stop,stops:Math.abs(i-start),minutes:Math.abs(i-start)*3+Math.max(1,Math.round(line.minutes/3))};const steps=[...cur.steps,segment];if(stop===to){const compact=[];for(const s of steps){const last=compact.at(-1);if(last&&last.lineId===s.lineId&&last.to===s.from){last.to=s.to;last.stops+=s.stops;last.minutes+=s.minutes}else compact.push({...s})}return{steps:compact,minutes:compact.reduce((n,s)=>n+s.minutes,0)+(compact.length-1)*6,changes:Math.max(0,compact.length-1)}}if(!seen.has(stop)&&cur.steps.length<2){seen.add(stop);queue.push({stop,steps,used:[...cur.used,line.id]})}}}}}return null;}
export {addTime};
